-- MySQL Script generated by MySQL Workbench
-- Wed May 31 14:22:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeringadministrator

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`OSOBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OSOBA` (
  `JMB` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `DatumRodjenja` DATE NOT NULL,
  `Pol` CHAR(1) NOT NULL,
  `Drzavljanstvo` VARCHAR(45) NOT NULL,
  `MjestoPrebivalista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`JMB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZAPOSLENI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZAPOSLENI` (
  `Osoba_JMB` INT NOT NULL,
  `KorisnickoIme` VARCHAR(45) NOT NULL,
  `Lozinka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Osoba_JMB`),
  CONSTRAINT `fk_Zaposleni_Osoba1`
    FOREIGN KEY (`Osoba_JMB`)
    REFERENCES `mydb`.`OSOBA` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VOLONTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VOLONTER` (
  `Zaposleni_Osoba_JMB` INT NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Zaposleni_Osoba_JMB`),
  CONSTRAINT `fk_Volonter_Zaposleni1`
    FOREIGN KEY (`Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`ZAPOSLENI` (`Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KORISNIK KAMPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KORISNIK KAMPA` (
  `Osoba_JMB` INT NOT NULL,
  `TipNesreće` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `VOLONTER_Zaposleni_Osoba_JMB` INT NOT NULL,
  PRIMARY KEY (`Osoba_JMB`),
  INDEX `fk_KORISNIK KAMPA_VOLONTER1_idx` (`VOLONTER_Zaposleni_Osoba_JMB` ASC) VISIBLE,
  CONSTRAINT `fk_table2_Osoba1`
    FOREIGN KEY (`Osoba_JMB`)
    REFERENCES `mydb`.`OSOBA` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KORISNIK KAMPA_VOLONTER1`
    FOREIGN KEY (`VOLONTER_Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`VOLONTER` (`Zaposleni_Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRATOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRATOR` (
  `Zaposleni_Osoba_JMB` INT NOT NULL,
  PRIMARY KEY (`Zaposleni_Osoba_JMB`),
  CONSTRAINT `fk_Administrator_Zaposleni1`
    FOREIGN KEY (`Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`ZAPOSLENI` (`Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STATUS_OBAVJESTENJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STATUS_OBAVJESTENJA` (
  `idSTATUS_OBAVJESTENJA` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSTATUS_OBAVJESTENJA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBAVJESTENJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBAVJESTENJE` (
  `idObavjestenje` INT NOT NULL AUTO_INCREMENT,
  `STATUS_OBAVJESTENJA_idSTATUS_OBAVJESTENJA` INT NOT NULL,
  `Datum` DATETIME NOT NULL,
  `ADMINISTRATOR_Zaposleni_Osoba_JMB` INT NOT NULL,
  PRIMARY KEY (`idObavjestenje`),
  INDEX `fk_OBAVJESTENJE_STATUS_OBAVJESTENJA1_idx` (`STATUS_OBAVJESTENJA_idSTATUS_OBAVJESTENJA` ASC) VISIBLE,
  INDEX `fk_OBAVJESTENJE_ADMINISTRATOR1_idx` (`ADMINISTRATOR_Zaposleni_Osoba_JMB` ASC) VISIBLE,
  CONSTRAINT `fk_OBAVJESTENJE_STATUS_OBAVJESTENJA1`
    FOREIGN KEY (`STATUS_OBAVJESTENJA_idSTATUS_OBAVJESTENJA`)
    REFERENCES `mydb`.`STATUS_OBAVJESTENJA` (`idSTATUS_OBAVJESTENJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OBAVJESTENJE_ADMINISTRATOR1`
    FOREIGN KEY (`ADMINISTRATOR_Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`ADMINISTRATOR` (`Zaposleni_Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MJESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MJESTO` (
  `idMjesto` INT NOT NULL AUTO_INCREMENT,
  `ImeMjesta` VARCHAR(45) NOT NULL,
  `Drzava` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMjesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STATUS_KAMPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STATUS_KAMPA` (
  `idSTATUS_KAMPA` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSTATUS_KAMPA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KAMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KAMP` (
  `idKamp` INT NOT NULL AUTO_INCREMENT,
  `Mjesto_idMjesto` INT NOT NULL,
  `Administrator_Zaposleni_Osoba_JMB` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `STATUS_KAMPA_idSTATUS_KAMPA` INT NOT NULL,
  PRIMARY KEY (`idKamp`),
  INDEX `fk_Kamp_Mjesto1_idx` (`Mjesto_idMjesto` ASC) VISIBLE,
  INDEX `fk_Kamp_Administrator1_idx` (`Administrator_Zaposleni_Osoba_JMB` ASC) VISIBLE,
  INDEX `fk_KAMP_STATUS_KAMPA1_idx` (`STATUS_KAMPA_idSTATUS_KAMPA` ASC) VISIBLE,
  CONSTRAINT `fk_Kamp_Mjesto1`
    FOREIGN KEY (`Mjesto_idMjesto`)
    REFERENCES `mydb`.`MJESTO` (`idMjesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kamp_Administrator1`
    FOREIGN KEY (`Administrator_Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`ADMINISTRATOR` (`Zaposleni_Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KAMP_STATUS_KAMPA1`
    FOREIGN KEY (`STATUS_KAMPA_idSTATUS_KAMPA`)
    REFERENCES `mydb`.`STATUS_KAMPA` (`idSTATUS_KAMPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERIOD BORAVKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERIOD BORAVKA` (
  `Korisnik kampa_Osoba_JMB` INT NOT NULL,
  `Kamp_idKamp` INT NOT NULL,
  `DatumDolaska` DATETIME NOT NULL,
  `DatumOdlaska` DATETIME NULL,
  PRIMARY KEY (`Korisnik kampa_Osoba_JMB`, `Kamp_idKamp`),
  INDEX `fk_Korisnik kampa_has_Kamp_Kamp1_idx` (`Kamp_idKamp` ASC) VISIBLE,
  INDEX `fk_Korisnik kampa_has_Kamp_Korisnik kampa1_idx` (`Korisnik kampa_Osoba_JMB` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik kampa_has_Kamp_Korisnik kampa1`
    FOREIGN KEY (`Korisnik kampa_Osoba_JMB`)
    REFERENCES `mydb`.`KORISNIK KAMPA` (`Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Korisnik kampa_has_Kamp_Kamp1`
    FOREIGN KEY (`Kamp_idKamp`)
    REFERENCES `mydb`.`KAMP` (`idKamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIP DONATORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIP DONATORA` (
  `idTipa` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DONATOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DONATOR` (
  `idDONATOR` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `TIP DONATORA_idTipa` INT NOT NULL,
  PRIMARY KEY (`idDONATOR`),
  INDEX `fk_DONATOR_TIP DONATORA1_idx` (`TIP DONATORA_idTipa` ASC) VISIBLE,
  CONSTRAINT `fk_DONATOR_TIP DONATORA1`
    FOREIGN KEY (`TIP DONATORA_idTipa`)
    REFERENCES `mydb`.`TIP DONATORA` (`idTipa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DONACIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DONACIJA` (
  `DONATOR_idDONATOR` INT NOT NULL,
  `KAMP_idKamp` INT NOT NULL,
  `IdDonacije` INT NOT NULL,
  PRIMARY KEY (`IdDonacije`),
  INDEX `fk_DONATOR_has_KAMP_KAMP1_idx` (`KAMP_idKamp` ASC) VISIBLE,
  INDEX `fk_DONATOR_has_KAMP_DONATOR1_idx` (`DONATOR_idDONATOR` ASC) VISIBLE,
  CONSTRAINT `fk_DONATOR_has_KAMP_DONATOR1`
    FOREIGN KEY (`DONATOR_idDONATOR`)
    REFERENCES `mydb`.`DONATOR` (`idDONATOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DONATOR_has_KAMP_KAMP1`
    FOREIGN KEY (`KAMP_idKamp`)
    REFERENCES `mydb`.`KAMP` (`idKamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SMJENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SMJENA` (
  `idSmjena` INT NOT NULL,
  `BrojSmjene` INT(1) NOT NULL,
  PRIMARY KEY (`idSmjena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VOLONTERSKI_ANGAZMAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VOLONTERSKI_ANGAZMAN` (
  `idVOLONTERSKI_ANGAZMAN` INT NOT NULL AUTO_INCREMENT,
  `VOLONTER_Zaposleni_Osoba_JMB` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  `SMJENA_idSmjena` INT ,
  `KAMP_idKamp` INT NOT NULL,
  PRIMARY KEY (`idVOLONTERSKI_ANGAZMAN`),
  INDEX `fk_VOLONTERSKI_ANGAZMAN_VOLONTER1_idx` (`VOLONTER_Zaposleni_Osoba_JMB` ASC) VISIBLE,
  INDEX `fk_VOLONTERSKI_ANGAZMAN_SMJENA1_idx` (`SMJENA_idSmjena` ASC) VISIBLE,
  INDEX `fk_VOLONTERSKI_ANGAZMAN_KAMP1_idx` (`KAMP_idKamp` ASC) VISIBLE,
  CONSTRAINT `fk_VOLONTERSKI_ANGAZMAN_VOLONTER1`
    FOREIGN KEY (`VOLONTER_Zaposleni_Osoba_JMB`)
    REFERENCES `mydb`.`VOLONTER` (`Zaposleni_Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VOLONTERSKI_ANGAZMAN_SMJENA1`
    FOREIGN KEY (`SMJENA_idSmjena`)
    REFERENCES `mydb`.`SMJENA` (`idSmjena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VOLONTERSKI_ANGAZMAN_KAMP1`
    FOREIGN KEY (`KAMP_idKamp`)
    REFERENCES `mydb`.`KAMP` (`idKamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INFRASTRUKTURA_KAMPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INFRASTRUKTURA_KAMPA` (
  `KAMP_idKamp` INT NOT NULL,
  `BrojKreveta` INT NOT NULL,
  `IzvorVode` VARCHAR(45) NULL,
  `IzvorStruje` VARCHAR(45) NULL,
  PRIMARY KEY (`KAMP_idKamp`),
  INDEX `fk_INFRASTRUKTURA_KAMP1_idx` (`KAMP_idKamp` ASC) VISIBLE,
  CONSTRAINT `fk_INFRASTRUKTURA_KAMP1`
    FOREIGN KEY (`KAMP_idKamp`)
    REFERENCES `mydb`.`KAMP` (`idKamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KREVET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KREVET` (
  `idKREVET` INT NOT NULL AUTO_INCREMENT,
  `RedniBrojKreveta` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `INFRASTRUKTURA_KAMP_idKamp` INT NOT NULL,
  PRIMARY KEY (`idKREVET`),
  INDEX `fk_KREVET_INFRASTRUKTURA1_idx` (`INFRASTRUKTURA_KAMP_idKamp` ASC) VISIBLE,
  CONSTRAINT `fk_KREVET_INFRASTRUKTURA1`
    FOREIGN KEY (`INFRASTRUKTURA_KAMP_idKamp`)
    REFERENCES `mydb`.`INFRASTRUKTURA_KAMPA` (`KAMP_idKamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICINSKE INFORMACIJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEDICINSKE INFORMACIJE` (
  `KORISNIK KAMPA_Osoba_JMB` INT NOT NULL,
  `KrvnaGrupa` CHAR(2) NULL,
  `HronicneBolesti` VARCHAR(45) NULL,
  `NeophodniLijekovi` VARCHAR(45) NULL,
  PRIMARY KEY (`KORISNIK KAMPA_Osoba_JMB`),
  CONSTRAINT `fk_MEDICINSKE INFORMACIJE_KORISNIK KAMPA1`
    FOREIGN KEY (`KORISNIK KAMPA_Osoba_JMB`)
    REFERENCES `mydb`.`KORISNIK KAMPA` (`Osoba_JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



       
#SELECT `OSOBA`.Ime,`OSOBA`.Prezime,`OSOBA`.JMB,Drzavljanstvo,DatumDolaska,DatumOdlaska,Status 
 #FROM `KORISNIK KAMPA`
#JOIN `OSOBA` ON `KORISNIK KAMPA`.`Osoba_JMB` = `OSOBA`.`JMB` 
 #JOIN `PERIOD BORAVKA` ON `KORISNIK KAMPA`.`Osoba_JMB` = `PERIOD BORAVKA`.`Korisnik kampa_Osoba_JMB` 
#JOIN `KAMP` ON `PERIOD BORAVKA`.`Kamp_idKamp` = `KAMP`.`idKamp` 
#WHERE `KAMP`.`Ime` = 'Camp 2';

-- SELECT o.Ime, o.Prezime,va.idVOLONTERSKI_ANGAZMAN, o.JMB, o.MjestoPrebivalista, k.Ime AS Kamp, va.StartDate, va.EndDate 
#FROM VOLONTER v 
#JOIN ZAPOSLENI z ON v.Zaposleni_Osoba_JMB = z.Osoba_JMB 
#                JOIN OSOBA o ON z.Osoba_JMB = o.JMB 
#                left JOIN VOLONTERSKI_ANGAZMAN va ON v.Zaposleni_Osoba_JMB = va.VOLONTER_Zaposleni_Osoba_JMB 
#                left JOIN KAMP k ON va.KAMP_idKamp = k.idKamp 
 #               WHERE o.Ime='Petar'; 
					
#SELECT o.Ime,o.Prezime,o.JMB,Drzavljanstvo,DatumDolaska,DatumOdlaska,Status 
#                    FROM `KORISNIK KAMPA` kk
#                    JOIN `OSOBA` o ON kk.`Osoba_JMB` = o.`JMB` 
 #                   JOIN `PERIOD BORAVKA` pb ON kk.`Osoba_JMB` = pb.`Korisnik kampa_Osoba_JMB` 
 #                   JOIN `KAMP` k ON pb.`Kamp_idKamp` = k.`idKamp` 
 #                   WHERE k.`Ime` = ?;
